DROP DATABASE TWITTER;
CREATE DATABASE TWITTER;
USE TWITTER;

CREATE TABLE LOGIN(
    USER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FULLL_NAME VARCHAR(60),
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(50),
    PICTURE_PATH VARCHAR(350)
);

CREATE TABLE TWEETS(
    USER_ID INTEGER,
    TWEET_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TWEET_TEXT VARCHAR(150),
    TWEET_ATTACHABLE VARCHAR(350),
    TWEET_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES LOGIN (USER_ID)
);

CREATE TABLE FOLLOWING(
    USER_ID INTEGER,
    FOLLOWING_USER_ID INTEGER,
    FOREIGN KEY (USER_ID) REFERENCES LOGIN (USER_ID),
    FOREIGN KEY (FOLLOWING_USER_ID) REFERENCES LOGIN (USER_ID)
);

DESCRIBE LOGIN;
DESCRIBE TWEETS;
DESCRIBE FOLLOWING;

CREATE VIEW user_tweets AS

    SELECT TWEETS.TWEET_ID, TWEETS.TWEET_TEXT, TWEETS.TWEET_ATTACHABLE,
        TWEETS.TWEET_DATE, LOGIN.FULLL_NAME, LOGIN.PICTURE_PATH, TWEETS.USER_ID
    FROM TWEETS
    INNER JOIN LOGIN
    ON TWEETS.USER_ID = LOGIN.USER_ID;

DESCRIBE user_tweets;